version: "3.8"
services:
  db:
    image: postgres:16-alpine
    container_name: mrlofy-db
    ports:
      - "5432:5432" # <-- এই পোর্ট ম্যাপিং নিশ্চিত করুন
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: melofy
